storage.port: 55280
storage.admin.port: 55281
storage.jetty.port: 55282
storage.directory: /waltz_storage/
zookeeper.connectString: zk:2181
zookeeper.sessionTimeout: 1000
cluster.root: /waltz_cluster
